### ISSUE TITLE
drop iframe

### ISSUE THREAD

**Issue by smellman** [unvt/unvt.github.io#2]
index.html show iframe but sometime the browser will be blank.

I recommend to use site generator like hugo.

**Comment by hfu** [comment]
Many thanks, @smellman. 

I also heard from a friend from some country that she cannot access hackmd. 

We may need to think about migrating to Hugo and something and rethink about the writing process. 

The challenge is to minimize psychological cost of editing the document while keeping a nice look. 

GitHub Wiki looks not so cool and I thought we needed nicer look thank GitHub pages Jekyll styles.

It looks to me that Hugo can be a good choice for us.

**Comment by hfu** [comment]
Thank you @smellman for the pull request. 

![ 2020-06-03 14 59 28](https://user-images.githubusercontent.com/18297/83601109-ec8e6600-a5aa-11ea-9e2b-d4c698f17b2d.jpg)

I am facing the problem of "User pages must be build from the master branch". It seems to me I can't source from gh-pages branch.

**Comment by smellman** [comment]
@hfu I create new PR #4

**Comment by hfu** [comment]
Yes, it works like a magic! Thank you, @smellman!

https://unvt.github.io/
